name: Keep Backend Awake

on:
  schedule:
    - cron: "0 12 */5 * *"     # every 5 days
  workflow_dispatch:         # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          echo "Pinging Frontend to keep backend alive..."
          curl -s https://findemy-wdn9.vercel.app/search?query=python
          echo "Ping completed"
